[package]
name = "repo_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
ubr = { path = "../unibranch" }
test_repo = { path = "../test_repo" }
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.81"
indoc = "2.0.5"
